[package]
name = "rem"
version = "0.1.0"
authors = ["ryann"]

[dependencies]
log = "0.3"
env_logger = "0.3"
backtrace = "0.3.0"
futures = "0.1.11"
futures-cpupool = "0.1.4"
tokio-core = "0.1.6"
tokio-service = "0.1.0"
tokio-proto = "0.1.1"